name: Publish Playwright Report

on:
  workflow_run:
    workflows: ["rodando com o reporter"]   # <<< NOME EXATO do workflow de testes
    branches: [main, master]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download HTML report artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: ./playwright-report
          run-id: ${{ github.event.workflow_run.id }}
          repository: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./playwright-report

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
